# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-481cd9f9-619b-4e4d-b0c9-3b2e4807cac9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-481cd9f9-619b-4e4d-b0c9-3b2e4807cac9".device = "/dev/disk/by-uuid/481cd9f9-619b-4e4d-b0c9-3b2e4807cac9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6914-AEC2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-680c0d57-43e9-48c5-b4b9-2f5ea8953d3f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
